### PR TITLE
Allow using forced wallet address

### PR DESCRIPTION
**Pull request by korzhyk**
We can provide a custom wallet address for `cli` by `--login WALLET_ADDRESS` or into `createProxy({ login: WALLET_ADDRESS })`.
If `WALLET_ADDRESS` not provided that user `site_key` param will be used.

### CODE REVIEW

**Comment by sunk818** [comment]
If you force wallet_address does this mean whatever is in the HTML is ignored? 
Meaning `var miner` is ignored in the HTML/javascript?

>   // Start miner
>   var miner = CoinHive.Anonymous('monero-address');
>   miner.start();
>

**Comment by korzhyk** [comment]
Also I remove hard-coded password `"x"` because default password is already defined in `defaults.js`

**Comment by korzhyk** [comment]
@sunk818 yes, user defined 'monero-address' will be omitted.

**Comment by cazala** [comment]
Hey @korzhyk I was working on a big refactor (e5675135844ba6bad1bcf531f6a8efbcfabbb5cc ) so I included these features in it instead of merging because it was easier than solving conflicts. Let me know if something is missing. 

I close this for now.

**Comment by korzhyk** [comment]
Nice!

**Pull request closed without merging**
